[build]
  publish = "/"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  publish = "."
  port = 9000
  staticServerPort = 4000  # Use this instead of targetPort for static servers
  framework = "#static"